Change the COPY command to execute a query.
When dumping a partitioned table the server responds with

ERROR:  cannot copy from partitioned table "foo"

so it is mandatory to execute a query to get all the data out of the
partitioned table.